### ISSUE TITLE
GUI issue?

### ISSUE THREAD

**Issue by sidneymurray** [lcnbeapp/beapp#22] opened 2023-11-27 13:23 UTC
Hi! I am running into some roadblocks with the BEAPP GUI.

My EEG data is super easy. Each file is just one 5-minute continuous segment of resting state data.

I'm just having trouble with some of the set up within the BEAPP gui. For example, it doesn't let me save all of my frequency bands and their ranges of Hz. It has weirdly saved just one. I also am not sure if I have the correct cap locations and channels entered since the net set ups it provides aren't exactly like the one we use (BioSemi32 is similar, but I need to switch out 2 channels for something else). 

When I try to run BEAPP after entering the parameters that it does me save, it gives me the following errors:

User chose to use an offset or

linenoise table, but no files listed in table

were found in source directoryC:\Program

Files\MATLAB\R2023a\eeglab14_1_2b\Dissertation

 

Error while evaluating UIControl Callback.

 

Error using  .

Unable to perform assignment because the left

and right sides have a different number of

elements.

Might there be a bug? 

Thank you!
Sidney

**Comment by ybraverman** [comment] 2023-12-08 23:58
Hi Sidney,

Awesome! Single quotes should be okay for this - two follow up questions to hopefully help troubleshoot it not finding your files:

1. Could you send a screenshot of what your "C:\Program Files\MATLAB\R2023a\eeglab14_1_2b\Dissertation" folder contains? 
2. Could you confirm that you've pointed to your specific beapp_file_info_table in your run template? To do this, you can check the format panel of your pre-processing settings and check the path highlighted in the red box.
<img width="311" alt="Screen Shot 2023-12-08 at 6 50 59 PM" src="https://github.com/lcnbeapp/beapp/assets/39894450/8f4d3108-66ec-4568-af0c-fb61ce152b24">

Regarding the net, I think this should just be 'Sidney32channel'. Once you add a new net to beapp, the net should get added to your "net library" under the name you specified. To confirm this, you can load the "net_library_options.mat" file in beapp/reference_data into matlab, open the variable, and check that there's a row with the net that you have added!

**Comment by sidneymurray** [comment] 2023-12-10 19:34
Thank you so much! You are right to delete the .ced in the table for net type.

Yes, so the problem is when I set my source directory to the folder with the .set data files, it looks like the folder is empty of all data when accessed from beapp. But if I access the data folder normally (like just sifting through my computer) all of the .set files are there with the right names as they appear in the tables. 

here is the error I just got. I'm also attaching a picture of my folder when accessed in beapp (no data appears) versus externally (all data is there).

![data present](https://github.com/lcnbeapp/beapp/assets/89815240/002a5459-bfd8-4148-bf27-d4fabc1908dd)
![data absent](https://github.com/lcnbeapp/beapp/assets/89815240/3278a58c-c96d-4e72-abe4-20b20046e10d)



![error_beapp_dec_10](https://github.com/lcnbeapp/beapp/assets/89815240/f7c0d6ec-6553-479c-bd72-9afadedb93c9)

**Comment by ybraverman** [comment] 2023-12-10 22:52
Hi Sidney,

Thanks for attaching these screenshots, that's super helpful! It makes sense to me that when choosing the source directory in beapp it wouldn't show the .set files - I believe it's programmed just to show folders so you can ultimately select the folder that has your files but not accidentally select a specific .set file as your source folder.

In that same panel, can you check the "select source file format" and make sure it is set to the .set option? I notice that beapp is trying to convert files from .mat to beapp format - so I think the problem is likely that you have set your "select source file format" to ".mat" instead of ".set" files in your run template. Beapp searches for all files with the source file type you specify, so it's likely looking (incorrectly) for any .mat files in the folder and finding none. Let us know if switching that to .set helps fix the problem!

**Comment by ybraverman** [comment] 2023-12-19 20:13
Hi Sidney,

Just following up, are you have more trouble or can I close this issue? Thank you!

**Comment by sidneymurray** [comment] 2023-12-20 16:24
Hi,

Thank you for following up. I am having more trouble. I have redownloaded BEAPP, but it says the new version is inaccessible. So I can't even run beapp_gui yet. I'm still trying to mess with it. I may just give up on BEAPP and use EEGLAB the old fashioned way. This has been very frustrating and long for no results yet 🙁

Sidney Murray
M.S. Neuroscience
M.A. Experimental Psychology
PhD Student in Behavior, Cognition, and Neuroscience
Nutritional Neuroscience Lab
________________________________

**Comment by sidneymurray** [comment] 2023-12-20 17:08
I fixed this problem I just sent, I was able to start running my data through but then got this error message:

'iirnotch' requires DSP System Toolbox.

Error in beapp_notch_filt (line 44)
[b,a]=iirnotch(wo,bw);

Error in batch_beapp_filt (line 97)
                EEG_curr_rec_period.data = beapp_notch_filt(EEG_curr_rec_period.data,file_proc_info.src_linenoise,file_proc_info.beapp_srate/2);

Error in beapp_main (line 188)
    grp_proc_info_main = batch_beapp_filt(grp_proc_info_main);

Error while evaluating UIControl Callback.

Sidney Murray
M.S. Neuroscience
M.A. Experimental Psychology
PhD Student in Behavior, Cognition, and Neuroscience
Nutritional Neuroscience Lab
________________________________

**Comment by ybraverman** [comment] 2023-12-20 17:20
Hi Sidney, 

Would you be able to send me an email at yael.braverman@childrens.harvard.edu? I'd be happy to touch base over zoom to help you get through these hurdles!

Best,
Yael

**Comment by lcnbeapp** [comment] 2024-01-22 20:17
Hi Sidney,

Thanks again for reaching out! Closing this issue now that we've identified you needed to import additional toolboxes from MATLAB, and we will include these in a revision of our user guide for new users, thank you!

**Closed by lcnbeapp** 2024-01-22 20:17 UTC
